Generalize reading of initial conditions for multi-dimensional data (#42)
* Generalize reading of initial conditions for multi-dimensional data

* Update writing of openPMD file

* Correct grid spacing

* in process_intensity_array_multispecies changed r_coords to grid_extent. Was getting: 'AttributeError: 'openpmd_api.openpmd_api_cxx.Mesh' object has no attribute 'position'' So I removed position attribute assignments (T.position and pop.position) as this attribute is only valid for particle data, not mesh data. Also mesh spatial is already properly defined through grid_spacing, grid_global_offset and axis_labels. I also was getting 'AttributeError: 'openpmd_api.openpmd_api_cxx.Mesh' object has no attribute 'reset_dataset'' so I changed reset_dataset and store_chunk calls to use mesh scalar components instaead of mesh objects directly.

* removed unnecessary return statement

* added interpolation

* fixed compilation error

* Avoid out-of-bound

* fixed indexing error

* More careful use of static variables

* Reduce the number of static variables

* Update objects

* Fix indentation

* Use proper size to copy

* Add position back

* Apply suggestions from code review

* Revert changes in radius and cell size

* Update sim_folder/run/inputs.2d.cyl

---------

Co-authored-by: Christian D McCombs <cmccombs@login10.chn.perlmutter.nersc.gov>
Co-authored-by: Christian D McCombs <cmccombs@login38.chn.perlmutter.nersc.gov>